# Importing Libraries

In [38]:
# Import necessary libraries for data manipulation, model building, and evaluation
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical

#Load the Prepared Data

In [40]:
# Load prepared data
X_train = pd.read_csv("data/X_train_prepared.csv")
y_train = pd.read_csv("data/y_train_prepared.csv")
X_test = pd.read_csv("data/X_test_prepared.csv")

# Convert Target to Categorical

In [44]:
# Convert target variable to categorical
y_train_categorical = to_categorical(y_train)

#Split Data into Training and Validation Sets

In [45]:
# Split the data into training and validation sets
X_train_split, X_val, y_train_split, y_val = train_test_split(X_train, y_train_categorical, test_size=0.2, random_state=42)

#Define the Model

In [46]:
# Define the Sequential model
model = Sequential([
    Dense(128, input_shape=(X_train.shape[1],), activation='gelu'),
    Dropout(0.5),
    Dense(64, activation='gelu'),
    Dropout(0.5),
    Dense(32, activation='gelu'),
    Dropout(0.5),
    Dense(16, activation='gelu'),
    Dropout(0.2),
    Dense(4, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Display model summary
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 128)               2816      
                                                                 
 dropout_8 (Dropout)         (None, 128)               0         
                                                                 
 dense_11 (Dense)            (None, 64)                8256      
                                                                 
 dropout_9 (Dropout)         (None, 64)                0         
                                                                 
 dense_12 (Dense)            (None, 32)                2080      
                                                                 
 dropout_10 (Dropout)        (None, 32)                0         
                                                                 
 dense_13 (Dense)            (None, 16)               

#Train the Model

In [47]:
# Train the model
history = model.fit(X_train_split, y_train_split,
                    epochs=50,
                    batch_size=32,
                    validation_data=(X_val, y_val))


Epoch 1/50
50/50 [==============================] - 2s 9ms/step - loss: 1.3938 - accuracy: 0.2650 - val_loss: 1.3263 - val_accuracy: 0.4950
Epoch 2/50
50/50 [==============================] - 0s 3ms/step - loss: 1.2639 - accuracy: 0.4350 - val_loss: 1.0774 - val_accuracy: 0.6550
Epoch 3/50
50/50 [==============================] - 0s 3ms/step - loss: 1.0724 - accuracy: 0.5156 - val_loss: 0.7802 - val_accuracy: 0.6925
Epoch 4/50
50/50 [==============================] - 0s 3ms/step - loss: 0.9108 - accuracy: 0.5981 - val_loss: 0.6503 - val_accuracy: 0.7750
Epoch 5/50
50/50 [==============================] - 0s 3ms/step - loss: 0.8117 - accuracy: 0.6494 - val_loss: 0.5658 - val_accuracy: 0.8600
Epoch 6/50
50/50 [==============================] - 0s 3ms/step - loss: 0.7255 - accuracy: 0.6862 - val_loss: 0.5117 - val_accuracy: 0.9025
Epoch 7/50
50/50 [==============================] - 0s 4ms/step - loss: 0.6850 - accuracy: 0.7081 - val_loss: 0.4666 - val_accuracy: 0.9600
Epoch 8/50
50/50 [==

#Evaluate the Model

In [50]:
from sklearn.metrics import accuracy_score

# Evaluate the model on the validation data
y_pred_probs = model.predict(X_val)
y_pred = np.argmax(y_pred_probs, axis=1)

# Convert y_val from categorical back to numerical labels
y_val_labels = np.argmax(y_val, axis=1)

# Print classification report
print(classification_report(y_val_labels, y_pred))

# Print confusion matrix
conf_mat = confusion_matrix(y_val_labels, y_pred)
print("Confusion Matrix:")
print(conf_mat)

# Calculate accuracy
accuracy = accuracy_score(y_val_labels, y_pred)
print(f"Accuracy: {accuracy:.4f}")


13/13 [==============================] - 0s 3ms/step
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       105
           1       0.90      0.97      0.93        91
           2       0.94      0.87      0.90        92
           3       0.96      0.96      0.96       112

    accuracy                           0.95       400
   macro avg       0.95      0.95      0.95       400
weighted avg       0.95      0.95      0.95       400

Confusion Matrix:
[[103   2   0   0]
 [  2  88   1   0]
 [  0   8  80   4]
 [  0   0   4 108]]
Accuracy: 0.9475
